// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SchoolManagementSystem.school;

#nullable disable

namespace SchoolManagementSystem.Migrations
{
    [DbContext(typeof(SchoolContext))]
    partial class SchoolContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("SchoolManagementSystem.school.Grade", b =>
                {
                    b.Property<int>("student_id")
                        .HasColumnType("int");

                    b.Property<int>("gr_hw")
                        .HasColumnType("int");

                    b.Property<int>("gr_pr")
                        .HasColumnType("int");

                    b.Property<int>("gr_t1")
                        .HasColumnType("int");

                    b.Property<int>("gr_t2")
                        .HasColumnType("int");

                    b.HasKey("student_id");

                    b.ToTable("Grades");
                });

            modelBuilder.Entity("SchoolManagementSystem.school.School", b =>
                {
                    b.Property<string>("sch_code")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("sch_dean_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sch_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sch_phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sch_type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("sch_code");

                    b.ToTable("schools");
                });

            modelBuilder.Entity("SchoolManagementSystem.school.Student", b =>
                {
                    b.Property<int>("StudentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StudentID"), 1L, 1);

                    b.Property<string>("Student_Fname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Student_Lname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("maj_code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("std_Dob")
                        .HasColumnType("datetime2");

                    b.HasKey("StudentID");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("SchoolManagementSystem.school.Grade", b =>
                {
                    b.HasOne("SchoolManagementSystem.school.Student", "student")
                        .WithMany("Grades")
                        .HasForeignKey("student_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("student");
                });

            modelBuilder.Entity("SchoolManagementSystem.school.Student", b =>
                {
                    b.Navigation("Grades");
                });
#pragma warning restore 612, 618
        }
    }
}
